package com.serverless;

import java.util.Map;

// This class <ApiGatewayResponse> is automatically generated by <serverless> cli command which using the template <aws-java-maven
public class Response {

	private final String message;
	private final Map<String, Object> input;

	public Response(String message, Map<String, Object> input) {
		this.message = message;
		this.input = input;
	}

	public String getMessage() {
		return this.message;
	}

	public Map<String, Object> getInput() {
		return this.input;
	}
}
